HitchHiker/HitchHiker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('hitch/', include('hitch.urls')),
    path('admin/', admin.site.urls),
]

HitchHiker/hitch/urls.py
from django.urls import path

from . import views

app_name = 'hitch'

urlpatterns = [
    path('', views.index, name='index'),
    path('mode', views.mode, name='mode'),
    path('<int:cadet>/rideMode', views.rideMode, name='rideMode'),
    path('<int:cadet>/rides', views.rides, name='rides'),
    path('<int:cadet>/oldRides', views.oldRides, name='oldRides'),
    path('<int:cadet>/driverMode', views.driverMode, name='driverMode'),
    path('vehicle', views.vehicle, name='vehicle'),
    path('rideForm', views.rideForm, name='rideForm'),
    path('<int:cadet>/oldDrives', views.oldDrives, name='oldDrives'),
]

HitchHiker/hitch/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.forms import ModelForm


class Cadet(models.Model):
    xnum = models.CharField(max_length=6)
    phoneNum = models.IntegerField()
    classYear = models.IntegerField()
    def __str__(self):
        return self.xnum

class Vehicle(models.Model):
    driver = models.ForeignKey(Cadet, on_delete=models.CASCADE)
    carMake = models.CharField(max_length=20)
    carModel = models.CharField(max_length=30)
    carColor = models.CharField(max_length=20)
    def __str__(self):
        return '%s %s %s' % (self.carMake, self.carModel, self.carColor)

class Destination(models.Model):
    destination = models.CharField(max_length=50)
    def __str__(self):
        return self.destination

class Ride(models.Model):
    destination = models.ManyToManyField(Destination)
    passengers = models.ManyToManyField(Cadet)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    departureTime = models.DateTimeField()
    seatsAvailable = models.IntegerField()
    storageAvailable = models.CharField(max_length=30)
    departureLocation = models.CharField(max_length=30)
    comments = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return '%s %s' % (self.vehicle.driver, self.departureTime)

HitchHiker/hitch/forms.py
from django import forms
from django.forms import ModelForm
from .models import Cadet, Vehicle, Ride, Destination

class cadetForm(forms.ModelForm):
    class Meta:
        model = Cadet
        fields = '__all__'

class vehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = '__all__'


class RideForm(forms.ModelForm):
    class Meta:
        model = Ride
        fields = '__all__'

class addRide(forms.ModelForm):
    class Meta:
        model = Ride
        fields = ('passengers',)

HitchHiker/hitch/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.shortcuts import get_object_or_404
from hitch.forms import cadetForm, vehicleForm, RideForm, addRide

from .models import Cadet, Vehicle, Ride, Destination

def index(request):
        if request.method == 'POST':
            form = cadetForm(request.POST)
            if form.is_valid():
                #Add the cadet to the database
                newCadet = form.save()
                cadet = newCadet.id
                context = {'cadet':cadet}
                #Go back to cadet list
                return render(request, 'hitch/mode.html', context)
        else:
            form = cadetForm()
        return render(request, 'hitch/index.html', {'form': form})

def mode(request):
    return render(request, 'hitch/mode.html')

def rideMode(request, cadet):
    context = {'cadet':cadet}
    return render(request, 'hitch/rideMode.html', context)

def rides(request, cadet):
    if request.method == 'POST':
        form = addRide(request.POST)
        if form.is_valid():
            #Add the cadet to the database
            newPassenger = form.save()
            #Go back to cadet list
            return HttpResponseRedirect('/hitch')
    ride_list = Ride.objects.all()
    context = {'ride_list':ride_list}
    return render(request, 'hitch/rides.html', context)

def oldRides(request, cadet):
    ride_list = Vehicle.objects.filter(driver=cadet)
    context = {'ride_list':ride_list, 'cadet': cadet}
    return render(request, 'hitch/oldRides.html', context)

def driverMode(request, cadet):
    context = {'cadet':cadet}
    return render(request, 'hitch/driverMode.html', context)

def vehicle(request):
        if request.method == 'POST':
            form = vehicleForm(request.POST)
            if form.is_valid():
                #Add the cadet to the database
                newCar = form.save()
                #Go back to cadet list
                return HttpResponseRedirect('/hitch/rideForm')
        else:
            form = vehicleForm()
        return render(request, 'hitch/vehicle.html', {'form': form})

def rideForm(request):
        if request.method == 'POST':
            form = RideForm(request.POST)
            if form.is_valid():
                #Add the cadet to the database
                newRide = form.save()
                #Go back to cadet list
                return HttpResponseRedirect('/hitch')
        else:
            form = RideForm()
        return render(request, 'hitch/rideForm.html', {'form': form})

def oldDrives(request, cadet):
    ride_list = Vehicle.objects.filter(driver=cadet)
    context = {'ride_list':ride_list, 'cadet': cadet}
    return render(request, 'hitch/oldDrives.html', context)

HitchHiker/hitch/templates/hitch/driverMode.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allerta+Stencil">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style>
.w3-allerta {
  font-family: "Allerta Stencil", Sans-serif;
}
</style>
<body class="w3-container w3-pale-blue">
<div class="w3-container w3-light-blue w3-center w3-allerta w3-padding-64">
  <h1 class="w3-jumbo w3-allerta">Hitch</h1>
  <p>This is a cadet Rideshare App</p>
</div>
  <a class="w3-border-white w3-border w3-col s6 w3-khaki w3-center w3-padding-64" href="{% url 'hitch:vehicle'  %}"><i class="glyphicon glyphicon-person">Enter a New Ride</i></a>
  <a class="w3-border-white w3-border w3-col s6 w3-khaki w3-center w3-padding-64" href="/hitch/{{ cadet }}/oldDrives"><i class="glyphicon glyphicon-car">See Your Previous Rides</i></a>
</body>

HitchHiker/hitch/templates/hitch/index.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allerta+Stencil">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style>
.w3-allerta {
  font-family: "Allerta Stencil", Sans-serif;
}
</style>
<body class="w3-container w3-pale-blue">
<div class="w3-container w3-light-blue w3-center w3-allerta w3-padding-64">
  <h1 class="w3-jumbo w3-allerta">Hitch</h1>
  <p>This is a cadet Rideshare App</p>
</div>
<div class="w3-card-4">

<div class="w3-container w3-khaki">
  <h2>Cadet Info</h2>
</div>
    <form class="w3-container w3-margin-16" action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input class="w3-input w3-khaki w3-btn" type="submit" value="Submit" />

    </form>

    </div>
</body>

HitchHiker/hitch/templates/hitch/mode.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allerta+Stencil">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<style>
.w3-allerta {
  font-family: "Allerta Stencil", Sans-serif;
}
</style>
<body class="w3-container w3-pale-blue">
<div class="w3-container w3-light-blue w3-center w3-allerta w3-padding-64">
  <h1 class="w3-jumbo w3-allerta">Hitch</h1>
  <p>This is a cadet Rideshare App</p>
</div>
<a class="w3-border-white w3-border w3-col s6 w3-khaki w3-center w3-padding-64" href="/hitch/{{ cadet }}/rideMode""><i class="glyphicon glyphicon-person">Rider</i></a>
<a class="w3-border-white w3-border w3-col s6 w3-khaki w3-center w3-padding-64" href="/hitch/{{ cadet }}/driverMode"><i class="glyphicon glyphicon-car">Driver</i></a>
</body>

HitchHiker/hitch/templates/hitch/oldDrives.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allerta+Stencil">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style>
.w3-allerta {
  font-family: "Allerta Stencil", Sans-serif;
}
</style>
<body class="w3-container w3-pale-blue">
<div class="w3-container w3-light-blue w3-center w3-allerta w3-padding-64">
  <h1 class="w3-jumbo w3-allerta">Hitch</h1>
  <p>This is a cadet Rideshare App</p>
</div>
  {% if ride_list %}
      {% for ride in ride_list %}
          <p>{{ride}}</p>
      {% endfor %}
  {% else %}
      <p>No rides are available.</p>
  {% endif %}
</body>

HitchHiker/hitch/templates/hitch/oldRides.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allerta+Stencil">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style>
.w3-allerta {
  font-family: "Allerta Stencil", Sans-serif;
}
</style>
<body class="w3-container w3-pale-blue">
<div class="w3-container w3-light-blue w3-center w3-allerta w3-padding-64">
  <h1 class="w3-jumbo w3-allerta">Hitch</h1>
  <p>This is a cadet Rideshare App</p>
</div>
  {% if ride_list %}
      {% for ride in ride_list %}
          <p>{{ride}}</p>
      {% endfor %}
  {% else %}
      <p>No rides are available.</p>
  {% endif %}
</body>

HitchHiker/hitch/templates/hitch/rideForm.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allerta+Stencil">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style>
.w3-allerta {
  font-family: "Allerta Stencil", Sans-serif;
}
</style>
<body class="w3-container w3-pale-blue">
<div class="w3-container w3-light-blue w3-center w3-allerta w3-padding-64">
  <h1 class="w3-jumbo w3-allerta">Hitch</h1>
  <p>This is a cadet Rideshare App</p>
</div>
<div class="w3-container w3-khaki">
  <h2>Cadet Info</h2>
</div>
    <form class="w3-container w3-margin-16" action="rideForm" method="post">
    {% csrf_token %}
    {{ form }}
    <input class="w3-input w3-khaki w3-btn" type="submit" value="Submit" />
</form>
</body>

HitchHiker/hitch/templates/hitch/rideMode.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allerta+Stencil">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style>
.w3-allerta {
  font-family: "Allerta Stencil", Sans-serif;
}
</style>
<body class="w3-container w3-pale-blue">
<div class="w3-container w3-light-blue w3-center w3-allerta w3-padding-64">
  <h1 class="w3-jumbo w3-allerta">Hitch</h1>
  <p>This is a cadet Rideshare App</p>
</div>
  <a class="w3-border-white w3-border w3-col s6 w3-khaki w3-center w3-padding-64" href="/hitch/{{ cadet }}/rides"><i class="glyphicon glyphicon-person">See All Rides</i></a>
  <a class="w3-border-white w3-border w3-col s6 w3-khaki w3-center w3-padding-64" href="/hitch/{{ cadet }}/oldRides"><i class="glyphicon glyphicon-car">See Your Previous Rides</i></a>
</body>

HitchHiker/hitch/templates/hitch/rides.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allerta+Stencil">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style>
.w3-allerta {
  font-family: "Allerta Stencil", Sans-serif;
}
</style>
<body class="w3-container w3-pale-blue">
<div class="w3-container w3-light-blue w3-center w3-allerta w3-padding-64">
  <h1 class="w3-jumbo w3-allerta">Hitch</h1>
  <p>This is a cadet Rideshare App</p>
</div>
  <ul class="w3-ul w3-border w3-khaki">
  <li><h2>Rides</h2></li>
  {% for ride in ride_list %}
      {% csrf_token %}
      <form action="rides" method="post">
        <li class="w3-bottombar w3-topbar w3-rightbar w3-leftbar w3-border-lightblue"> {{ride.destination}} {{ride.passengers}} {{ride.departureTime}}</li>
      <input type="submit" value="add me to this ride" />
  {% endfor %}
</body>

HitchHiker/hitch/templates/hitch/vehicle.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allerta+Stencil">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style>
.w3-allerta {
  font-family: "Allerta Stencil", Sans-serif;
}
</style>
<body class="w3-container w3-pale-blue">
<div class="w3-container w3-light-blue w3-center w3-allerta w3-padding-64">
  <h1 class="w3-jumbo w3-allerta">Hitch</h1>
  <p>This is a cadet Rideshare App</p>
</div>
<div class="w3-container w3-khaki">
  <h2>Cadet Info</h2>
</div>
    <form class="w3-container w3-margin-16" action="vehicle" method="post">
    {% csrf_token %}
    {{ form }}
    <input class="w3-input w3-khaki w3-btn" type="submit" value="Submit" />
</form>
</body>